### ISSUE TITLE
FIP Discussion: Reduce PoRep verification time by reducing graph parents generation cost

### ISSUE THREAD

**Issue by nicola** [filecoin-project/FIPs#102]
Facts:
* According to preliminary calculations, about half of the time spent in verifying a PoRep proof goes into generating the correct indices of the parents of the challenged nodes (from now *challenged parents*)
* Challenged parents are currently independent per proof and they depend on the randomness at the height of PreCommit.

Potential proposals that could evolve into a FIP:

* **Proposal 1: Add cache to verification**:
  * Full nodes must keep in cache the full graph in order to generate parents efficiently by reading memory (~1GiB)
  * Pro:
    * No major change, only gas cost adjustments and requirement of graph cache
    * It will improve today's proofs (no requirement on SnarkPack)
  * Cons:
    * Large memory/storage requirement for full node (note that they are already storing a very large state, so likely not too bad afterall)
* **Proposal 2: Generate parents once for aggregated precommits (SnarkPack only)**
  * Given a ProveCommitAggregate, for all sectors precommitted at the same epoch, only generate the parents once (since they will share the same randomness). In this way, it will be more rational for miners to reduce their gas cost by PreCommittAggregate and then ProveCommitAggregate their proofs
  * Pros:
    * No mem requirement as in 1
  * Cons:
    *  Miners need to time things right to minimize costs
    * Only works with SnarkPack
    * Miners may PreCommit across epochs, so we may not realize the full 50% gas reduction
* **Proposal 3: Same randomness for all precommits in a window**
  * Instead of randomness being assigned per pre-commit, only generate randomness every X blocks, every precommitted before X will use randomness at X. This means that for all sectors precommitted at position X, they will all have the same randomness, hence parents only need to be calculated once every X for all miners.
  * Pros:
    * No mem requirement as in 1
    * Can realize 50% gas reduction
    * Should work also without SnarkPack

There may be other solutions that we did not consider. Let us know what are your thoughts on the three proposals.

Once this gets more solidified we can turn it into an FIP proposal.

**Comment by irenegia** [comment]
>Challenged parents are currently independent per proof and they depend on the randomness at the height of PreCommit.

They depend of the randomness at the height that is 150 epochs after PreCommit.
So, for Proposal 3 this means that sectors precommited 150 epochs before X use the randomness at X (not just before X). 

 CC @lucaniz

**Comment by anorth** [comment]
Is (2) purely an implementation optimization, no protocol change? That is, could a miner implement it now (after FIP-0013) and enjoy faster block validation times. That'd be great, and unless we want to update gas costs to _assume_ such an optimization, doesn't need a FIP. That is, we can implement it first and FIP the gas cost change later, perhaps alongside proposal 3 to increase its impact.

**Comment by kaitlin-beegle** [comment]
Hey @nicola! Given the scope of network changes that have been implemented since this idea was first introduced, are all three of these approaches still purposeful and valid? 

If so, let's maintain them! However, until work on a FIP draft actually commences, we'll need to migrate this post out of the Issues log and into the [FIPs Discussion Forum](https://github.com/filecoin-project/FIPs/discussions). 

To maintain yourself as the author/maintainer of the post, simply copy+paste the text from this discussion thread and into a new one in the Forum! Apologies it's so manual- in the future, I'm hopeful that Github will support moving threads between forum spaces. 

If you don't care about being the issue maintainer, or if I don't hear back in the next few days, I'll migrate the issue for you and tag you as the original author. 

Thanks!
