### ISSUE TITLE
FIP Proposal: Upgrade regular deal to verified deal

### ISSUE THREAD

**Issue by ozhtdong** [filecoin-project/FIPs#116]
## Simple Summary

Allow miner to send an upgraded verified deal after the piece data has been sealed and sector has been landed on chain.

## Abstract

Today if client/miner wants to take advantage of Filecoin Plus program, the process is client send DataCap request to notary, with supplemental in formations provided, notary approve the request and assign DataCap to the client, then client start the deal process by sending proposal(s) with VerifiedDeal field marked "true", and miner go through the rest of deal process steps, while being part of Filecoin Plus, miners enjoy the higher quality adjusted power and clients enjoy lower storage price, a de factor binding has been imposed between filecoin plus onboarding process and deal-seal process by making successful onboarding process as the pre-condition before deal-seal

This proposal is aiming to break this de factor dependency without changing or compromising the Filecoin Plus Client Onboarding process, but just wants to introduce an additional deal upgrade message to be allowed to submit to the chain to either 1, make the previous regular deal to be an "verified deal" or 2, To supplement deal information related to a CC sector which sealed piece data with meaningful content

## Change Motivation

1, Given the benefit of Filecoin Plus to both clients and miners, clients might tend to apply for DataCap before store their data in the chain, and DataCap approval process normally take days even weeks, and it's possible that eventually only partial or even no DataCap is granted, therefore it could be a barrier or a delay factor for clients to land their data in the network. Decouple Filecoin Plus and propose deal will encourage client to store their data in Filecoin first and apply DataCap in parallel or later.

2, Although the network storage power is over 6EiB, majority of it is Committed Capacity with zero data in it. Miners are not intended to use existing "CC upgrade" to make it a sector with deals because of no extra economic motivation, given the "post verification" mechanism in place, expect deals might be increasing sharply and it could be economic efficient to leverage existing committed capacity with zero piece by CC upgrade, therefore the overall piece data size parentage could be increased w.r.t overall network storage power. (For reference, in date of Jun 4, In the total 768062 precommit message, only 2 were "ReplaceCapcity" )

3, For CC sectors with non zero data piece (assume to implement in FIP "Pack arbitrary data in CC sectors and be able to upgrade them to verified data later"), no re-seal will be needed to upgrade the CC sector to a "deal sector"

## Design Rationale

Two scenario will need to be considered in design:
1, New "Upgrade deal" proposal needs to be defined with verified field to be true, and new "UpggadeStorageDeal" needs to be added to the Market Actor, to link the existing original deal to the sector already committed to the network, and update the quality adjusted power.
2, With another FIP "Pack arbitrary data in CC sectors and be able to upgrade them to verified data later" implemented, a complemented proposal need to be defined to the CC sector, and a "ComplemntStorageDeal" needs to be 
added to the Market Actor to link the complement deal to the existed CC sector.

## Backwards Compatibility

There will be no impact to the existing sectors/deals committed to the chain

## Security Considerations

Seal process will keep as it is, there will be no chance to bring sectors to the network in faster manner by this proposal.
The DataCap approval process will not be no change (or even be strengthen for notary to retrieve the piece data before grant the DataCap), therefore there will be no shortcut for clients/miners to bring more quality adjusted power nonauthentic way.

## Incentive Considerations

1, Encourage client to bring more business data to the network without waiting for DataCap proving process
2, Encourage miner to leverage CC upgrade more often
3, For "CC sectors with data piece", no re-seal needed for CC upgrade.

**Comment by benjaminh83** [comment]
Seems like an interesting option, but I just played it through in my head, and from a miner perspective, I might see an issue on the unverified -> verified deal upgrade. 
Currently most miners allow verified deals at 0 FIL per epoch, as they gain faster power, but still charge maybe 0.00000001 FIL per epoch for regular unverified deals. 
So if I have a client which has applied and waiting for a datacap, but has not been approved and wants to onboard the data now as unverified - what do we do then? I would not allow the client to store unverified at 0 FIL, only with a promise that there might be a datacap in the future and the deals might be upgraded to verified... So I would keep my filter on the price for unverified deals and make the client pay.. **But what actually happens then when the client gets the datacap and wants to upgrade the deals to verified? Will the miner be able to revert the initial cost per epoch back to 0, and will the miner be hit with the missing x9 collateral, that has not been paid yet (as the sealed sector was unverified)?**

**Comment by kernelogic** [comment]
What does this mean? Upgrade any existing deals without notary nor datacap?

**Comment by ozhtdong** [comment]
> Seems like an interesting option, but I just played it through in my head, and from a miner perspective, I might see an issue on the unverified -> verified deal upgrade.
> Currently most miners allow verified deals at 0 FIL per epoch, as they gain faster power, but still charge maybe 0.00000001 FIL per epoch for regular unverified deals.
> So if I have a client which has applied and waiting for a datacap, but has not been approved and wants to onboard the data now as unverified - what do we do then? I would not allow the client to store unverified at 0 FIL, only with a promise that there might be a datacap in the future and the deals might be upgraded to verified... So I would keep my filter on the price for unverified deals and make the client pay.. **But what actually happens then when the client gets the datacap and wants to upgrade the deals to verified? Will the miner be able to revert the initial cost per epoch back to 0, and will the miner be hit with the missing x9 collateral, that has not been paid yet (as the sealed sector was unverified)?**

That is a very valid question! I think there are two options here. 1, Miner is setting an separate ask price which target for "possible" upgrade deal, which could be in the range between normal price and 0, and let the market decide what price that will be. 2, Or we can set an "refund" mechanism in consensus, miner can set like 80% refund rate for example, client pay for the normal fee in the deal initiation, but once client get her DataCap later and the deal get upgraded, client get refunded by 80% for the rest of unpayed part. 

Miner has to add the x9 collateral, otherwise the upgrade wouldn't be successful.

**Comment by ozhtdong** [comment]
> What does this mean? Upgrade any existing deals without notary nor datacap?

No, upgrade deal must require client has the datacap proved by notary.

**Comment by steven004** [comment]
I would agree this is good idea, which will encourage miners to store valuable data into the network. 
At the same time, I would think the storage price and client collateral is already in a deal, so that we can put the collateral change into the upgrading logic, including calculating the new collateral for both client and provider, and also how much should be stored in pay channel, and make necessary adjustments if enough balance remaining or fail the upgrading.  Basically, the x9 miner collateral will be added in, and some refund to client may happen if the new price is lower.

**Comment by ozhtdong** [comment]
> I would agree this is good idea, which will encourage miners to store valuable data into the network.
> At the same time, I would think the storage price and client collateral is already in a deal, so that we can put the collateral change into the upgrading logic, including calculating the new collateral for both client and provider, and also how much should be stored in pay channel, and make necessary adjustments if enough balance remaining or fail the upgrading. Basically, the x9 miner collateral will be added in, and some refund to client may happen if the new price is lower.

Thanks for elaborate it in a detailed manner!

**Comment by happyicdecream** [comment]
Very good proposal,a win-win situation for both the clients and miners.

**Comment by MasonfWilliam** [comment]
Nice proposal

**Comment by flyworker** [comment]
It is a useful proposal, but notary need to have a sampling tool for testing the data.
Applicant need to submit the proof

**Comment by steven004** [comment]
> It is a useful proposal, but notary need to have a sampling tool for testing the data.
> Applicant need to submit the proof

This is key for filecoin plus success. Currently for public data storing in Filecoin, we could publicly verify the data, and provide a convincing proof of the value possibly, however, for private data, we still need a mechanism. I am running randomly check the pieces of the data stored in Filecoin network, but still, how to publicly validate those data, it is still a question.

**Comment by ozhtdong** [comment]
Regarding the storage fee difference between verified/regular deal, here is a simple solution seems to be fair to both client and miner.
1, While client propose a regular deal, a regular storage fee will be attached and charged later when PublishStorageDeal is on chain just like any other regular deal.
2, After client acquire DataCap later, an "upgrade deal" proposal will be sent to miner and miner sent a "UpgradeStorageDeal" on chain, along with recalculating the quality storage power and Initial pledge, a proportional storage fee (original storage fee * (end epoch - upgrade deal epoch) / (end epoch - start epoch)) will be returned to client.

**Comment by MatrixStorage** [comment]
Matrix Storage is an enterprise dedicated to real data storage and promoting the implementation of decentralized storage ecology.  We've been looking at the ecological value of IPFS and Filecoin since the end of 2020. Since its launch in April, 2020, Matrix Storage has been committed to linking the upstream and downstream industries of ecology, providing practical solutions for clients, storage providers and notaries, and exploring and discovering better technical solutions. To build a decentralized storage platform based on IPFS and Filecoin network.  
In the course of our business, we encountered some practical problems:

**Ⅰ High threshold for real data storage**
What is currently attractive to storage providers is the 10x power gain from verified data storage. It costs 10x the pledge and deals sending gas, which is heavily dependent on DataCap application at the same moment. So far only 2.436 PiB DataCap has been allocated, while the total network power has reached 11.6279 EiB. Some storage providers think that storing verified data is only 9x gas less than cc sealing, but the process is very troublesome.
1. To obtain DataCap
2. To contact the big storage providers for technical changes bacause some big storage providers are hosting operations for small storage providers.
3. Full storing cycle is long, and income reduces. Although the sealing process of verified data is consistent with CC sealing, it is far less fast than CC sealing due to data transmission and other objective conditions.
How to make storage providers more willing to store verified data becomes an important issue.  Our platform pays certain economic incentives to storage providers who are willing to join Matrix Storage platform. But it still does not guarantee to attract more storage providers to join.  

**Ⅱ The waste of resources**
At present, the network 11EiB effective power, the vast majority of storage is meaningless data. Now, let's say that if we're cooperating with big clients, such as Youku, TikTok, etc. We have to rebuild the nodes for storage,  and we can't reuse existing storage space. Some countries have tightened regulations on the industry. To lower the threshold to verified data storage is a matter of great urgency. To give participants enough confidence to continue to participate in this great project.

**Ⅲ DataCap allocation is just the beginning**  
FIL+ currently exists that DataCap sealed in deals accounted for a lower proportion of the DataCap allocation. FIL+ recently proposed a half-year target. We believe that DataCap allocation alone is not the target, but verified data sealed in deals is.  This cannot be done without the support of storage providers for verified data storage.

This issue solves the problem of resource waste and lowers the threshold for storage  providers to seal verified data.  
In view of the rapid development of the verified data storage ecosystem, we recommend that this issue, CC sector can be replaced for free, can be realized as soon as possible. To attract more service providers to join, to serve more verified clients.  
**It's not just deal, it's trade.**

**Comment by anorth** [comment]
I understand the motivation for this proposal, and think it's reasonable. I don't immediately see a good reason why, in the long term, the protocol should prevent this.

It's quite difficult to implement at the moment with the coupling between the storage market and miner actors, quality-adjusted power mechanisms, etc. It will become much much more feasible after removing QA-power with #121 and removal of other coupling between the miner and storage market. 

Then it would become a policy option for the storage market contracts.

**Comment by kaitlin-beegle** [comment]
@ozhtdong hello there! This is a great proposal and, to @anorth's point, may be technically feasible once the storage market gets decoupled from miner actors.  Multiple implementation teams are working on this at the moment; I could see there being a lot of traction around a FIP like this after the FVM introduction in the v16 network upgrade (which will land early in 2022Q2) 

In order to keep track of this issue, I will be migrating this over to the [FIPs Discussion Forum](https://github.com/filecoin-project/FIPs/discussions)!
