### ISSUE TITLE
FIP Discussion: CC Sector Repair Tool

### ISSUE THREAD

**Issue by realChainLife** [filecoin-project/FIPs#149]
Discussion issue for the [CC Sector Repair Tool](https://github.com/catthehunter/devgrants/blob/patch-1/open-grant-proposals/Sector%20Repair%20Tool.md) from PR([#279](https://github.com/filecoin-project/devgrants/pull/279)). 

## Motivation
By reworking and repairing wrong CC sectors, it will reduce sector loss damage and penalties for requiring to terminate sectors, and fix repair issues during sector maintenance.

@catthehunter and team have proposed three development approaches:

* Redo the CC sector-related functional code and release it with Lotus-Miner new version updates
* Redo the CC sector-independent program code and Lotus-redo project code
* Redo CC sector-independent program executables (binary), Lotus-redo (binary)

A developer grant was approved for the creation of this tool and a draft FIP will be shared soon.

**Comment by momack2** [comment]
After reading the grant proposal - my understanding is this aims to build a tool/library that can re-create a sector (and replace it from the Filecoin protocol's perspective) if an error is encountered. It allows a storage provider to seal a new sector with the same ticket/cid/etc and use it to slot _in place_ of a broken sector. So if you have a deals sector, you set up the exact same sector info/data/contents as before, and do the same sealing process to generate a new sector, which the Filecoin blockchain should then accept **_instead_** of the old sector when it comes to wPoSt, collateral, deal rewards, etc. 

I think this **does** likely have core protocol implications (ex, the sector was sealed with different randomness, it may have a different lifetime and collateral than a new sector sealed later, your contract with the deal-maker may or may not be upheld, etc). I'd like @nicola and @zixuanzh to comment on this from the security/cryptoecon perspectives early so you know what constraints/roadblocks to navigate! 

FWIW - I know there have been some conversations about making CCSectors more "fungible" between folks like @anorth @Kubuxu etc - so maybe they also have thoughts or ideas to contribute to your approach.

**Comment by catthehunter** [comment]
Thanks guys, we would love to have the community to discuss this proposal. We want more ideas to make our proposal and Filecoin better!

**Comment by jennijuju** [comment]
@catthehunter Could you please clarify if the proposed scope is what @momack2 suggests, which is be able to recover an locally errored sector by replacing it with a new sector then keep proving the same data,
or the poposal was to create a tool thats being built in implementations so that if a sector data is missing, it re-generates the data needed for proving the same onchian sector?

If it's the latter, I dont think there is any protocol changes would needed and instead of a FIP, this should be discussion in community/implementation forums for community input.

**Comment by catthehunter** [comment]
@jennijuju  The proposal is to creat a tool that is being built in implementations.

**Comment by jennijuju** [comment]
> @jennijuju The proposal is to creat a tool that is being built in implementations.

@kaitlin-beegle With this being said, i'd suggest transferring this isseu to the implementation forum or community forum.
By definition, `Filecoin Improvement Proposals (FIPs) are the primary mechanism by which the Filecoin community can submit, discuss, and approve changes relevant to the **Filecoin network**.` and  this proposal is to add a new feature to implementation rather than changes to the Filecoin Network.

Tho @momack2 's points are very interesting and i think we can create a new issue for discussing something similar to "replacing a locally errored onchain sector with a new sector"

**Comment by kaitlin-beegle** [comment]
@jennijuju I agree- I think there was some initial confusion around which technical pathway to take for this work, but it sounds like it's been clarified.  To be as explicit as possible, this means that the team will carry forth with their first proposed solution: 

"Redo the CC sector-related functional code and release it with Lotus-Miner new version updates."

@catthehunter does this sound correct to you?

**Comment by catthehunter** [comment]
@kaitlin-beegle   Yes, this sounds correct to me. So what's next?

**Comment by kaitlin-beegle** [comment]
@catthehunter great! Then @jennijuju's guidance is correct.  This issue does not require a FIP because the technical pathway only requires a modification to Lotus functional code.  This is therefore a tool, not a core protocol enhancement, and does not need to go through the FIP process.  

Since the DevGrant for this work was already approved, there is no other required community deliberation.  We're good to go! (CC: @realChainLife) 

@jennijuju, I'm not sure how/if the Lotus team collaborates/coordinates on external tool development.  Would you mind providing some guidance as to whether or not this proposal needs to be moved into the Lotus repo?

**Comment by jennijuju** [comment]
> @catthehunter great! Then @jennijuju's guidance is correct. This issue does not require a FIP because the technical pathway only requires a modification to Lotus functional code. This is therefore a tool, not a core protocol enhancement, and does not need to go through the FIP process.
> 
> Since the DevGrant for this work was already approved, there is no other required community deliberation. We're good to go! (CC: @realChainLife)
> 
> @jennijuju, I'm not sure how/if the Lotus team collaborates/coordinates on external tool development. Would you mind providing some guidance as to whether or not this proposal needs to be moved into the Lotus repo?

Yes- they can gather community input in https://github.com/filecoin-project/lotus/discussions/categories/ideas

**Comment by catthehunter** [comment]
@jennijuju  Do I need to open a new pull request to post this proposal in discussion channel?

**Comment by kaitlin-beegle** [comment]
Follow-up: after connecting with @realChainLife, this request can be closed.  

@catthehunter and team will continue to work through the DevGrant process, with @realChainLife as their primary point of contact.  Since this doesn't need a FIP, there is no need to keep the discussion open here.  At the moment, the team is writing detailed design specs, which will be sent to the Lotus team for review.  Any subsequent review or code building will be managed directly by the Lotus team.
