### ISSUE TITLE
Revert FIP repo architecture to fix broken links, and prioritize humans again

### ISSUE THREAD

**Issue by jbenet** [filecoin-project/FIPs#165]
- **Prior Context.** Some recent PRs changed the repo so that automatic websites could be built. that is cool, and a great idea. :+1: (thanks for doing that!) However that changed the layout of the repo to prioritize tooling and broke links.
- **Prioritize humans** This repo is for humans, and linking in various community forums. Lots of important deep links into the FIPs have broken, and need to be restored. Changing the layout of this repo to prioritize tooling is not good, and its layout should revert back.
- **Tooling in branches or subdirs:** You can automatically generate things and so on, but please move that into other branches (auto builds) or subdirectories (build bots can look into subdirs easier than humans + rewriting links everywhere on the internet).
- **Git History.** Also, please bring back the git history for all FIPs, that is pretty important community information. If the history is lost on github, I'm sure some of us have repo copies and we can likely find it.

**Comment by momack2** [comment]
PR in question was https://github.com/filecoin-project/FIPs/pull/125/files -- @bmann - can you help revert the rename of the "FIPS" folder to "_fips"?

![image](https://user-images.githubusercontent.com/618519/133621818-9e5cd04f-05f8-472b-82c5-5e2624f5afe0.png)

**Comment by bmann** [comment]
Hi @momack2 @jbenet -- sorry this got committed without having this discussion first. 

Yes, of course I'll help make this work with the FIPS original name.

I opted to build it in the most minimal operational way so that it would "just work" in GHPages if need be. I'm still waiting for feedback on #158 on how the deployment actually works and/or if we can get consensus on how to make it easiest to deploy to a filecoin website URL.

My preference would be to prioritize humans and generate a website build per PR, so that FIPS authors can see what the rendered version would look like.

**Comment by kaitlin-beegle** [comment]
Thanks, @bmann.  Confirming (outside of Slack) that I'm also meeting with @andyschwab to help push this issue along and will update publicly once we have a path forward. 

Additionally, if we are going to build the FIPs site from a separate branch, I'd like to restore the FIPs table to the README file. I think it's fine if this table exists in both places, but for now it's very necessary to have in the Github repo for quick reference.

**Comment by kaitlin-beegle** [comment]
Closing issue; PR has been submitted (thanks, @bmann!)

**Comment by jbenet** [comment]
thanks very much! 😄
