### ISSUE TITLE
Add return value to WithdrawBalance

### ISSUE THREAD

**Issue by steven004** [filecoin-project/FIPs#26]
**Background**
Both miner and market actors have `WithdrawBalance` methods. 
- WithdrawBalance in Miner actor is for owner to withdraw the vested block rewards, which is the only way the owner could get FIL from a miner actor;
- WithdrawBalance in Market actor is for clients or providers to withdraw a specified amount from the balance held in escrow. 

However, either method is actually an attempt to withdraw a specified amount, it could be successful even when the available balance is less than required amount, that means, the actual amount withdrawn is equal to or less than the amount specified in the method parameters, and the method always return `nil`, so that, there is no way to get how much amount actually withdrawn if we check the chain status and message info, e.g. from CLI or explorer. 

**Proposal**
Simply add a return value to the method to indicate the actual withdrawn amount. 

This will improve the visibility and traceability of FIL flow. This is important especially for miners who need to have a very clear balance sheet and financial report.

**Comment by anorth** [comment]
This sounds great to me.

It's part of an open discussion, but this also sounds like a change that's inconsequential enough that we might not need to use the FIP process for it. Since it changes the actors API it will need to wait for the next major release (v3) of actors, but we're planning for that later this year.

@whyrusleeping @dignifiedquire @momack2 should we use the FIP process for this, or just go straight to implementation.

**Comment by dignifiedquire** [comment]
I would error on the side of creating a FIP for now, even if it is a simple one.

**Comment by kaitlin-beegle** [comment]
Hi @anorth! I'm currently working to audit all open FIP discussion items so that we can triage existing issues and flag priorities that may have been missed. 

It looks like this issue was lost in the bundle of FIPs that were implemented prior to the Actors v5 launch.  Is this the case? If so, we should reintroduce the idea and write a FIP draft.

**Comment by anorth** [comment]
Thanks, sounds good to me

**Comment by kaitlin-beegle** [comment]
This was implemented as [FIP0020](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0020.md)!
