### ISSUE TITLE
Create FIP draft for Decouple FIL+ 

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/FIPs#429]
https://github.com/filecoin-project/FIPs/discussions/313 is scoped in nv17 - we need an FIP for it!

**Comment by jennijuju** [comment]
Ideally we should have the FIP draft by Sep 2nd
and leave 3 weeks for last call, feedbacks and revisions (including implementation).

**Comment by kaitlin-beegle** [comment]
PR has been opened.  Closing issue!

**Comment by jennijuju** [comment]
hi - I opened this for nv17 eng. task track purpose. Let’s close when the fip pass last call, thank you!

**Comment by anorth** [comment]
@jennijuju I don't think the FIPs repo should be bent to serve engineering tracking. I would probably have waited until the PR was merged, but I don't think holding it out for Last Call is right.

Unless we revamp to track every FIP process with an issue, which could be handy to help keep track of FIP status, but purely for its own good.

**Comment by dkkapur** [comment]
@anorth Re the current FIP draft merged in https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0045.md - I wanted to confirm my understanding / check on a few things. 

@kaitlin-beegle @jennijuju if there is a better place to do this, let me know. Thank you!

1. Does the client address in the Allocation and Claim structs have any downstream impact in terms of deal/QAP extension for SPs? The way the FIP reads today (which is reasonable, just want to confirm) - anyone can create Allocations for the specific CID/SP and the SP could make a claim against it. Does the first client address need to be maintained in either of the Structs for future renewals? The only potential case I could find for this was in `Extension of claim term by client` where it looks like the original client listed in the claim struct is the only one able to increase a claim length up to the 5y max. 
2. In the case that a client does extend a claim up to 5y but the sector expires / if the SP does not extend it? Is it returned to the allocations table or burned?
3. There is no deduplication across clients on the allocations table since the client address is a field in the allocation, correct? Theoretically, as long as there are multiple identical allocations, an SP can make multiple deals with the same CID (serially, waiting to seal each one before initiating the next) and get QAP for each of them. This is the same behavior as today but could be a good opportunity for future optimization.
4. Can multiple allocations can be made from the same client address to the same SP for the same piece CID?
6. Will `MinimumVerifiedAllocationTerm` need to be updated to 12 months if FIP 0036 passes?
7. Sanity check: is there any particular reason why `MarketDefaultMaximumAllocationTerm` needs to be 90d? Seems like anything between 60d and TermMin should work correct?
8. With this FIP, (please correct me if this is wrong) a deal cannot be sealed into a sector that has a lifetime that is 90d longer than the deal length. SPs that proactively extend existing sectors beyond reasonable deal length terms (i.e., anything over 21 months today) may preclude them from being able to snap future deals into those sectors. 

cc @ribasushi @ZenGround0
