### ISSUE TITLE
 Some words to fil

### ISSUE THREAD

**Issue by CodingJzy** [filecoin-project/FIPs#439]
Some words to fil:
    I'm a big fan of fil, but I'm getting more and more disappointed in you guys, and I'm not going to complain about fil price today. I'm just talking about your efficiency and attitude.

1. Can the official website of fil be updated? Too old and not fresh at all. Looks like a MLM website. Take a look at how beautiful and elegant the official website of other projects is.I just found a few projects here, all of which are members of many people. Wouldn't it be nice to let fil's fans have a home and a home?

<img width="253" alt="image" src="https://user-images.githubusercontent.com/44855157/185772272-bc16464c-211e-428c-8791-eec7879eef49.png">

2. Many projects have their own tg groups with thousands of members. There are Chinese and English groups, where various ecological news and project progress can be posted. And fil does. The fil project has never been operated by any official group.

3. FVM was announced in November last year. Now the first phase has not been completed. I heard that it will be released in 
 2023.1-2023.2. Why? Why is it delayed every time? Is the team development ability not good? Or developers don't want to write code? Or is the rust language difficult? The blockchain has been developed for so long, and it is not difficult to develop an evm now, and many projects are implemented in rust. near, polkadot, and sol are all developed in the rust language, including the new public chain aptos and sun. They can come in so fast, you are slow like a turtle. You stand on the shoulders of giants and avoid many pits. Even so, you don't make announcements every time you delay? Every time I go to the official website to secretly change June to August, August to November, and November to 2023. Is this your attitude? You keep fans and developers waiting? Wait until the day lilies are cool. Every time an Ethereum merger is announced, there will be a delay. It’s okay to delay, but the attitude is good. At least let the outside world know where your difficulties are, instead of saying nothing.
@jbenet @Stebalien

**Comment by kaitlin-beegle** [comment]
Hi @CodingJzy - I am going to be closing this issue, since this is not the forum for this feedback.  However, there seems to be some confusion, and I hope I can be of help. 

For 'website', I am not sure what you mean.  The [Filecoin project](https://filecoin.io/), as originated by Protocol Labs, and [Filecoin Foundation](https://fil.org/) each have websites.  However, the Filecoin community primarily organizes itself across Github, Slack, and Discord.  The Chinese community is mostly located on WeChat.  There are tens of thousands of community contributors across these groups.  

Please let me know if you have more specific feedback about these, or need help accessing any of them. Unfortunately, I am not sure what your screenshot is referencing. 

Lastly, the first stage of the Filecoin Virtual Machine was successfully implemented in [network v16](https://github.com/filecoin-project/tpm/blob/master/Network%20Upgrades/v16.md)!  For information about the next stages of FVM development and implementation, you can ask your question in the #fil-fvm channel in Slack, or check out the [website](https://fvm.filecoin.io/)!

**Comment by CodingJzy** [comment]
> Hi @CodingJzy - I am going to be closing this issue, since this is not the forum for this feedback. However, there seems to be some confusion, and I hope I can be of help.
> 
> For 'website', I am not sure what you mean. The [Filecoin project](https://filecoin.io/), as originated by Protocol Labs, and [Filecoin Foundation](https://fil.org/) each have websites. However, the Filecoin community primarily organizes itself across Github, Slack, and Discord. The Chinese community is mostly located on WeChat. There are tens of thousands of community contributors across these groups.
> 
> Please let me know if you have more specific feedback about these, or need help accessing any of them. Unfortunately, I am not sure what your screenshot is referencing.
> 
> Lastly, the first stage of the Filecoin Virtual Machine was successfully implemented in [network v16](https://github.com/filecoin-project/tpm/blob/master/Network%20Upgrades/v16.md)! For information about the next stages of FVM development and implementation, you can ask your question in the #fil-fvm channel in Slack, or check out the [website](https://fvm.filecoin.io/)!

o, o, o, o, o
