### ISSUE TITLE
 Proposal on the extension of the V1 proof sector lifetime

### ISSUE THREAD

**Issue by deltazxm** [filecoin-project/FIPs#56]
**Summary**
It is currently not possible to extend the life cycle of the V1 proof sectors. This has caused a huge loss to the miners who sealed the V1 proof sectors in early days. Sealed sectors should only take windowPoSt challenges, security issues would not be involved. So we propose the V1 proof sectors' life cycle could be extended. 

If the life cycle of these sectors cannot be extended, there will be a lot of sealing computation resources wasted to seal these sectors again. If miners have to seal sectors again, it will take much more collaterals and gas. More messages will make the chain congested, and other miners will have to pay more high gas fees too. 

If the life cycle of V1 proof sectors is set to 180 days, miners would experience horrible loss and may cause even greater losses due to gas fee issues. 

**Improvement Goal**
Allow the life cycle of V1 proof sectors to be able to extend like v8 proof sectors. Please see the detailed improvement plan: [https://github.com/filecoin-project/specs-actors/pull/1310]

**Comment by coder-lb** [comment]
This is a good proposal. If V1 proof sectors can't be extended, many sealing machine resources will be wasted to seal sectors again. Filecoin should be a project with less energy consumed, then it will be more competitive in storage markets.

**Comment by coder-lb** [comment]
If a huge number of sectors can't be extended, there will be several side effects. If the miners seal sectors again, it will take much more time, and much more gas. More messages will make the chain congested, and other miners will pay more high gas fees, too.

**Comment by maobisheng** [comment]
Totally agree to extend life cycle of v1 proof sectors.

**Comment by flyworker** [comment]
If the purpose is for better storage market, instead of extend, it should be upgrade sectors with data deals, otherwise those sectors are useless in storage market.

**Comment by ElecRoastChicken** [comment]
This is definitely a good suggestion for network development. At present, the high gas cost is due to the congestion of message pool. If V1 sector cannot be extended life cycle will lead to quite a number of re-sealing, which will bring a new round of congestion peak, that is not conducive to the reduction of gas cost, but also bring pressure (can be avoidable, just extend life cycle) to the network.

**Comment by steven004** [comment]
@deltazxm good proposal to discuss. 

I would suggest adding a **Motivation** section and a **Security Consideration** section. The motivation is clear that there are half (possibly more) of power are sealed using V1, and massive computing resources consumed for that. To allow the extension of V1 sectors is environment friendly way to keep the power of Filecoin. In addition, it is also good to maintain Filecoin's stability. 

However, there might be security concerns, which is not very clear to many miners. To me, I could understand why upgrading from V1 to 1.1 for security issue, but it is more impact on the sealing process, but how's its impact to verification. @nicola may add more to this.

**Comment by deltazxm** [comment]
If impact to verification.Then the current v1 sector also has security problem.So,I think there is no problem with windowPOST.

**Comment by kacee-song** [comment]
This is by design, motivated by security considerations for the V1 proof.

**Comment by PatrickDeuse** [comment]
> If the life cycle of these sectors cannot be extended, there will be a lot of sealing computation resources wasted to seal these sectors again. If miners have to seal sectors again, it will take much more collaterals and gas. More messages will make the chain congested, and other miners will have to pay more high gas fees too.

this is just not true. this would imply that right now sectors are not being sealed because of existing v1 sectors. 

if those sectors expire the baseline will change, that's the first thing. and then resources that would be used for sealing anyways would be used to "reseal" those sectors. i doubt that there will be an overall increase in CC sector sealing activity if we just let those sectors expire.

**Comment by shibowe** [comment]
> > If the life cycle of these sectors cannot be extended, there will be a lot of sealing computation resources wasted to seal these sectors again. If miners have to seal sectors again, it will take much more collaterals and gas. More messages will make the chain congested, and other miners will have to pay more high gas fees too.
> 
> this is just not true. this would imply that right now sectors are not being sealed because of existing v1 sectors.
> 
> if those sectors expire the baseline will change, that's the first thing. and then resources that would be used for sealing anyways would be used to "reseal" those sectors. i doubt that there will be an overall increase in CC sector sealing activity if we just let those sectors expire.

"reseal" still take much collaterals and gas? ?

**Comment by shibowe** [comment]
> > If the life cycle of these sectors cannot be extended, there will be a lot of sealing computation resources wasted to seal these sectors again. If miners have to seal sectors again, it will take much more collaterals and gas. More messages will make the chain congested, and other miners will have to pay more high gas fees too.
> 
> this is just not true. this would imply that right now sectors are not being sealed because of existing v1 sectors.
> 
> if those sectors expire the baseline will change, that's the first thing. and then resources that would be used for sealing anyways would be used to "reseal" those sectors. i doubt that there will be an overall increase in CC sector sealing activity if we just let those sectors expire.

"reseal" still take much collaterals and gas? ?

**Comment by PatrickDeuse** [comment]
> "reseal" still take much collaterals and gas? ?

reseal here means sealing other sectors to replace them. you  have to keep in mind that collateral and fees for v1 sectors were paid with testnet FIL - at a market price of exactly 0. so no one ever paid for them.

**Comment by deltazxm** [comment]
> > "reseal" still take much collaterals and gas? ?
> 
> reseal here means sealing other sectors to replace them. you have to keep in mind that collateral and fees for most, if not all, v1 sectors were paid with testnet FIL - at a market price of exactly 0. so no one ever paid for them. the reason that this issue exists is not to protect the network or keep the baseFee low - but to go on earning real FIL with sectors that were paid for with testnet FIL - and as you can imagine they have a way higher ROI than sectors that needed to be sealed with real FIL.

All sectors before November 26 have this problem.Not only SR.

**Comment by cwhiggins** [comment]
Sectors are meant to expire. Miners cannot control the length of time a client makes a deal for. There is no reason to extend these sectors. We will all lose power, yes, that is how the system is designed.

**Comment by KaptinLin** [comment]
I don't think it's good idea extend life cycle of v1 proof sectors. A lot of v1 sectors are SP1 sectors, some of them are not stable and it should be termination for secure reason.

**Comment by kidcdf** [comment]
> I don't think it's good idea extend life cycle of v1 proof sectors. A lot of v1 sectors are SP1 sectors, some of them are not stable and it should be termination for secure reason.

what kind of "not stable"?

**Comment by kidcdf** [comment]
> > "reseal" still take much collaterals and gas? ?
> 
> reseal here means sealing other sectors to replace them. you have to keep in mind that collateral and fees for most, if not all, v1 sectors were paid with testnet FIL - at a market price of exactly 0. so no one ever paid for them. the reason that this issue exists is not to protect the network or keep the baseFee low - but to go on earning real FIL with sectors that were paid for with testnet FIL - and as you can imagine they have a way higher ROI than sectors that needed to be sealed with real FIL.

The rewards obtained in the testnet are used to pay those miners who have made great contributions to the testnet. They are willing to follow Filecoin when the mainnet is uncertain, and spend a lot of time and energy on machines, labor costs, and operation and maintenance. , Laid the foundation for the successful launch of the mainnet, so the testnet coin is also valuable. Now that the sector cannot be extended, it means that it will cost 150% more pledge cost to reseal it. This is unnecessary. Is this a draw from the bottom? ?

> > "reseal" still take much collaterals and gas? ?
> 
> reseal here means sealing other sectors to replace them. you have to keep in mind that collateral and fees for most, if not all, v1 sectors were paid with testnet FIL - at a market price of exactly 0. so no one ever paid for them. the reason that this issue exists is not to protect the network or keep the baseFee low - but to go on earning real FIL with sectors that were paid for with testnet FIL - and as you can imagine they have a way higher ROI than sectors that needed to be sealed with real FIL.

The rewards obtained in the testnet are used to pay those miners who have made great contributions to Filecoin. They are willing to follow Filecoin when the mainnet is uncertain, and spend a lot of time and money on machines, labor costs, operation and maintenance. , Laid the foundation for the successful launch of the mainnet, so the testnet coin is surely valuable. 

Now these sectors cannot be extended, it means that it will cost 150% more pledge cost and gas to reseal it. This is unnecessary and unreasonable. No one has specifically explained why it has affected the security and stability of the mainnet. Should such a decision on a decentralized network not be more cautious in soliciting community suggestions?

**Comment by PatrickDeuse** [comment]
> The rewards obtained in the testnet are used to pay those miners who have made great contributions to Filecoin. They are willing to follow Filecoin when the mainnet is uncertain, and spend a lot of time and money on machines, labor costs, operation and maintenance. , Laid the foundation for the successful launch of the mainnet, so the testnet coin is surely valuable.

neither pledge nor sealing costs of these sectors were part of the rewards. the testnet coin shouldn't have had any value at all. not then, not now, not ever. 

> Now these sectors cannot be extended, it means that it will cost 150% more pledge cost and gas to reseal it. This is unnecessary and unreasonable. No one has specifically explained why it has affected the security and stability of the mainnet. Should such a decision on a decentralized network not be more cautious in soliciting community suggestions?

not "now" - they never were able to be extended later.

- sp1 sectors cost 0% and got 100% of the power. 
- others pay 100% for 100% of the power. 

we cannot cement this inequality forever on the chain. the stability will suffer. cannot talk about security - i assume that if there are issues no one will tell you, for obvious reasons and we just let them phase out.

**Comment by kidcdf** [comment]
Sectors before November 24 will not to be extended, but between October 15 and November 24, we have purchased a large amount of real coins to seal data,  these r "real" sectors!  why these sectors will now also be "killed"?

**Comment by kidcdf** [comment]
> > The rewards obtained in the testnet are used to pay those miners who have made great contributions to Filecoin. They are willing to follow Filecoin when the mainnet is uncertain, and spend a lot of time and money on machines, labor costs, operation and maintenance. , Laid the foundation for the successful launch of the mainnet, so the testnet coin is surely valuable.
> 
> neither pledge nor sealing costs of these sectors were part of the rewards. the testnet coin shouldn't have had any value at all. not then, not now, not ever.
> 
> > Now these sectors cannot be extended, it means that it will cost 150% more pledge cost and gas to reseal it. This is unnecessary and unreasonable. No one has specifically explained why it has affected the security and stability of the mainnet. Should such a decision on a decentralized network not be more cautious in soliciting community suggestions?
> 
> not "now" - they never were able to be extended later.
> 
> * sp1 sectors cost 0% and got 100% of the power.
> * others pay 100% for 100% of the power.
> 
> we cannot cement this inequality forever on the chain. the stability will suffer. cannot talk about security - i assume that if there are issues no one will tell you, for obvious reasons and we just let them phase out.

Sectors before November 24 will not to be extended, but between October 15 and November 24, we have purchased a large amount of real coins to seal data, these r "real" sectors! why these sectors will now also be "killed"?

**Comment by coder-lb** [comment]
> > > 
> > 
> > 
> > not "now" - they never were able to be extended later.
> > 
> > * sp1 sectors cost 0% and got 100% of the power.
> > * others pay 100% for 100% of the power.
> > 
> > we cannot cement this inequality forever on the chain. the stability will suffer. cannot talk about security - i assume that if there are issues no one will tell you, for obvious reasons and we just let them phase out.
> 
> Sectors before November 24 will not to be extended, but between October 15 and November 24, we have purchased a large amount of real coins to seal data, these r "real" sectors! why these sectors will now also be "killed"?

Agree. At least sectors between Oct 15 and Nov 24 should be extended.

**Comment by KaptinLin** [comment]
It was not a good idea to shift the SP1 sector to the mainnet at that time. These sectors should be expired. It's not fair to the new miners.

Now that big miners have more and more advantages, new miners have to spend more to join the network. This is not conducive to decentralization.

**Comment by thecreation** [comment]
The life cycle of these v1 sectors should not be extended in order to increase the profits of big miners. They have acquired a lot. There should be more opportunities for new miners and small miners to join the network.

**Comment by maobisheng** [comment]
> It was not a good idea to shift the SP1 sector to the mainnet at that time. These sectors should be expired. It's not fair to the new miners.
> 
> Now that big miners have more and more advantages, new miners have to spend more to join the network. This is not conducive to decentralization.

At least sectors between Oct 15 and Nov 24 should be extended.

**Comment by deltazxm** [comment]
At least sectors between Oct 15 and Nov 24 should be extended.

**Comment by steven004** [comment]
The only strong reason for objection of extension is security problem, what is that? Is it that the bug in previous proof makes it proving faster? I would believe that is still safe for years before the hardware power is improved significantly for tens of times. If the concern is about related to this, how about allowing one time for perhaps one or two years?

Or any other one not unveiled?

**Comment by nicola** [comment]
I wrote a comment here a while ago: https://github.com/filecoin-project/specs-actors/issues/1309#issuecomment-758715926

**Comment by deltazxm** [comment]
So the conclusion will not be extension?There are different voices in the community.We want extension the sector.At least sectors between Oct 15 and Nov 24. @nicola

**Comment by shibowe** [comment]
> So the conclusion will not be extension?There are different voices in the community.We want extension the sector.At least sectors between Oct 15 and Nov 24. @nicola

Oct 5 ~ Nov 24 ?  
It refer to 2020 ?

**Comment by deltazxm** [comment]
Yes,After mainnet

**Comment by flyworker** [comment]
if keep the power between Oct 5 ~ Nov 24, does that mean only the sectors before this period is insecure? 

No ,if you want to keep , keep all of them, if it is expired due to security, expired all of them.

**Comment by KaptinLin** [comment]
Before encapsulating v1, this rule has been defined. You cannot modify the rules of v1 just because v2 and v3 allow expansion. If this is the case, if there is v4 later, if there are new rules, should v1, v2, and v3 be adjusted?

**Comment by KaptinLin** [comment]
Since these v1 sectors are voluntarily sealed, we cannot ask for changed because we have the same rules as v2、v3. They just change. And we have already enjoyed the benefits of v1. If allowed, it is not conducive to subsequent participants.

**Comment by steven004** [comment]
> I wrote a comment here a while ago: [filecoin-project/specs-actors#1309 (comment)](https://github.com/filecoin-project/specs-actors/issues/1309#issuecomment-758715926)
> 

Thanks @nicola , this was mentioned earlier. `There is a risk that a year+ from now` makes me think about another option, how about just limit the overall expiration time for V1, e.g. only 540 days allowed for V1, and 5 years (the current setting) for other versions. This makes things more fair, since some of the  v1 sectors with 540 day expiration setting, and others less.

**Comment by PatrickDeuse** [comment]
letting them expire will most likely affect just a minority of miners and a tiny minority of sectors. if they are a known security risk in 1 year they should get eliminated as soon as possible to not have that thread vector around for longer time. we should have kicked them as soon as the vulnerability became known, called it "tough shit" and moved on...

**Comment by thecreation** [comment]
We already know that these sectors have unsafe factors, why not just let it go? Making the entire network healthier is the primary decision factor. And it did not harm anyone's interests. When sealing v1 sectors, miners knew that these sectors were about to expire. What's more, most of the sectors in it are free. I cannot understand the practice of many big miners in order to improve their benefits regardless of the health of the entire network.

**Comment by xiachongbuyubing** [comment]
+1

**Comment by Bruce2020FIL** [comment]
我支持V1到期后续期，老胡你要有良心啊。不要做没心没肺家伙。YOU KNOW????

**Comment by jennijuju** [comment]
> 我支持V1到期后续期，老胡你要有良心啊。不要做没心没肺家伙。YOU KNOW????

Personal attack is not welcomed.

**Comment by jennijuju** [comment]
Another option the community should investigate together is whether its possible to upgrade v1 sectors to v1.1 sector so that they are more secure and can be extended.

**Comment by deltazxm** [comment]
> Another option the community should investigate together is whether its possible to upgrade v1 sectors to v1.1 sector so that they are more secure and can be extended.

If possible, this is the best practice.

**Comment by PatrickDeuse** [comment]
put a deal inside and there you go.

**Comment by Fatman13** [comment]
> There is a risk that a year+ from now, with highly pipelined custom hardware (less likely to be software - but not impossible), one may able to avoid storing 100% of the sector and still succeed at WindowPoSt.**

Every encryption created ever has security problems. Question is, is it economically viable to exploit such issue? Will institutions (like Google) around the world use its quantum computing power to crack Satoshi's wallet? If they were to invoke the nuclear options, BTC will be plummeting. Not sure if there exists people outside of community who are well-funded and determined to develop ASIC machines and destroy filecoin. Or maybe there are?

**Comment by Xman-destroyer2021** [comment]
An extension was agreed, and that time is now approaching.If lengthen, after waiting for network scale to grow, drop this part to calculate force again, the likely influence won't be so big.In the early days of the network, if most of the computing power falls off, it won't be friendly to all miners.
If we are worried about network security, we can consider whether we can provide taps from the foundation or F099 to increase the computational power for these miners, otherwise we may pay three times the cost at that time.

**Comment by danilowhk** [comment]
The Sector from testnet doesn't have any deals and doesn't help in any way to keep the network healthy, on the contrary, it brings risk because of the V1 exploits and is almost like a barrier to new miners since it's a huge disadvantage.

**Comment by ArthurWang1255** [comment]
V1 proof sectors deserve extension. First, these V1 proof sectors are not free there were thousands of servers maintaining them(I doubt the intention of those ones who are ).Second, the large fluctuation of storage volume itself is a security risk to the filecoin network.

**Comment by ArthurWang1255** [comment]
V1 proof sectors deserve extension. First, these V1 proof sectors are not "free", there are thousands of servers maintaining them (I doubt the intentions of those ones who are not supporting this proposal, early miners put in money and time before others doing so to build filecoin system and don't deserve a fair sector? ). Secondly, the large fluctuation of storage volume itself is a security risk to the filecoin network. In the end, what we are pursuing is a larger scale of storage and a moving forward consensus. Giving the V1 proof sectors extension they deserve and let the community put the eyes on the future.

**Comment by ArthurWang1255** [comment]
> V1 proof sectors deserve extension. First, these V1 proof sectors are not "free", there are thousands of servers maintaining them (I doubt the intentions of those ones who are not supporting this proposal, early miners put in money and time before others doing so to build filecoin system and don't deserve a fair sector? ). Secondly, the large fluctuation of storage volume itself is a security risk to the filecoin network. In the end, what we are pursuing is a larger scale of storage and a moving forward consensus. Giving the V1 proof sectors extension they deserve and let the community put the eyes on the future.

Only if fairness is not important in the community and system, then big miners will take over the right to speak. It's harmful to the community and the whole ecosystem of filecoin.

**Comment by jennijuju** [comment]
Allow v1 sectors to have 540 days in epoch is proposed in [fip-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md) as one of the options to this topic. The proposal is still in DRAFT and the community should work on the `product consideration`,  detailed `security consideration` and other sections before it can move forward to the next stage.

**Comment by f8-ptrk** [comment]
there is still no argument for how this improves the network.

**Comment by timguo-ipfs** [comment]
V1 type sectors deserved to be extended as 540days. 
It's fair for the miners who sealed it and stress tested the whole network earlier to make the Filecoin network what it is today.

**Comment by f8-ptrk** [comment]
> V1 type sectors deserved to be extended as 540days.
> It's fair for the miners who sealed it and stress tested the whole network earlier to make the Filecoin network what it is today.

i am sorry, but that is not an argument. why should we keep a security risk (for all people involved!!!) on the chain for the "benefit" of a few miners? to make the network more secure for everyone we should terminate these sectors forcefully as soon as possible.

**Comment by timguo-ipfs** [comment]
> > V1 type sectors deserved to be extended as 540days.
> > It's fair for the miners who sealed it and stress tested the whole network earlier to make the Filecoin network what it is today.
> 
> i am sorry, but that is not an argument. why should we keep a security risk (for all people involved!!!) on the chain for the "benefit" of a few miners? to make the network more secure for everyone we should terminate these sectors forcefully as soon as possible. keeping them longer then necessary (and to be straight forward here: no one needs those sectors! they are just "another sector"... can be replaced with new ones at all times) is not fair to everyone involved with filecoin, we deserve security risks to be eliminated as soon as they are known!

respect your thoughts, not an argument at all!
everyone has their ideas to be shared here, that means the idea can be out in different perspectives.
that's why we have a discussion.

**Comment by coder-lb** [comment]
V1 proof sectors are not free, especially between Oct 15 and Nov 24. Miners who spent a lot of FILs to pledge between Oct 15 and Nov 24 will be long term players and the most loyal supporters of the Filecoin ecosystem, since they were willing to invest real money  in a project just started.
At the beginning of mainnet, many other miners dare not seal and they kept on waiting, until they were sure that they could get enough benefits. So we could see the gas fee was low right after the mainnet launched, and got very high in December.  This is normal, but it also shows that early miners can bring better loyalty to the network.
Of course, None of the above is an excuse for security. But with current hardware, it is very hard to use the previous bug to pass WindowPoSt without store all of data now. I agree with @steven004, probably we can extend the sectors to 540 days. It will still be secure. Some miners set the expired days to less than 540 days only because they thought it was more flexible. Who knew the sectors would be treated selectively so that it could not be extended In Oct? Who knew the gas fee would be very high so that re-sealing these sectors would cost more in Oct? The security of Filecoin requires people from the entire ecosystem to work out ways and maintain them together, not only just avoiding a possible issue in the future. With more miners and more power, Filecoin will be more secure.

**Comment by f8-ptrk** [comment]
here are the arguments i see so far pro/contra implementing this FIP.

pro implementing: 
- financial advantage for those miners who have large amounts of these sectors sealed

contra implementing:
- financial disadvantage for miners without large amounts of these sectors sealed
- keeping a security risk on the chain for ~360 more days

there is no argument so far how implementing this would improve filecoin.

**Comment by steven004** [comment]
I'd emphasizes two things here for further discussion: 
1) Fair-play. To limit life time of a proof-type of sectors is more fair. Remember people set the expiration date of a sector to 180, 540 or any other days before the extension is disabled for V1. 
2) This is not to extend V1 sectors for more days, while there are more than half of V1 sectors' life time is 540 days, to limit the overall lifetime to 540 days DOES NOT extend this proof-type sectors beyond its existing time in the network. The bound is still there.

**Comment by deltazxm** [comment]
FIP0014 not only satisfies the need for arrangement, but also does not lose fairness. It is a perfect progress that everyone can accept. We hope it can be implemented as soon as possible. @jennijuju

**Comment by mxz9102** [comment]
Since these sectors are using V1. To avoid a security risk for the whole network, letting them expire is the best solution from my opinion. So I object the extension of the V1 sector life cycle.

**Comment by Fatman13** [comment]
> there is no argument so far how implementing this would improve filecoin - in my eyes.

@f8-ptrk, I think one of the problems may stem from the fact that core team made the decision that V1 proof can't be extended pretty much silently. Decisions that may affect that many miners should at least go through some level of discussion.

**Comment by KaptinLin** [comment]
I don’t think it’s fair to the new miners. I worked with them, they complained that the early big miners had so many cheap sectors that it became more difficult for them to participants on the network. This may not be conducive to decentralization.

**Comment by momack2** [comment]
I think preference from a protocol perspective is still to **enable an easy way to upgrade and reseal v1 sectors into v1.1 sectors** so they have the same storage power security guarantees, but don't have to take up chain space (and gas/collateral fees) again. 

Given this isn't ready for the sectors expiring in the next few months, I think the lotus team is somewhat agnostic about whether the community should allow 6 month sectors to share the 540 day expiry (that is the default for all new sectors) or expire now. The security concerns here **absolutely** mean these sectors should not be renewed past that 540 day limit - but the level of concern is the same for all v1 sectors (most of which are 540 day sectors, not 180 day sectors). Slight preference to "expire now" since that's the easiest and avoids another state upgrade in the next few weeks - but OK with either of these two options.

For deciding between those options, maybe we can use the new https://filpoll.io tool to collect community sentiment across miners / token holders / clients / etc. Thoughts on that?

I absolutely expect the v1 sector expiration to be a concern again in a year - and it **will not be an option** to extend v1 sectors without resealing at that time due to security concerns. In preparation for that, I think community members like @steven004 @deltazxm @coder-lb @maobisheng etc should help identify / implement the best path to upgrade v1 sectors into v1.1 sectors if maintaining power and minimizing chain overhead/fees is desired.

**Comment by steven004** [comment]
Agreed, @momack2 . 
Could we start the poll soon? we may just need a few days to complete the poll while broadcasting it via slack, wechat, twitter, which will reach most miners and community members quickly. And then, we could have about one week time to prepare for the new release once major part of the voters agree the proposal, so that we can meet the first hump of the expiration of V1 sectors.

**Comment by deltazxm** [comment]
Hope to start the poll  as soon as possible. @jennijuju.Once the conclusion is reached, publish the conclusion as soon as possible. This issue has been discussed for a long time.

**Comment by arajasek** [comment]
Hoping to start the poll tomorrow!

**Comment by deltazxm** [comment]
> start the poll

How can start a poll?

**Comment by jennijuju** [comment]
> > start the poll
> 
> How to initiate a poll

It will be setup and announced to the community later today.

**Comment by danlessa** [comment]
# The Impact of V1 Sector Expirations on Filecoin Storage and Cryptoeconomics

## Background context

Shortly after Filecoin liftoff, a security issue was reported with the v1 proofs. The issue was fixed in v1.1 proofs, which were introduced in the Filecoin network version 7 upgrade, on November 25th, 2020. As a result of this upgrade:
- All new sectors had to use v1.1 proofs
- v1 sectors were allowed to remain on the network, **but were NOT allowed to be extended**

Since the security of these sectors is not critically compromised, we can consider allowing their extension, which was proposed in [FIP-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md). This report details the storage and cryptoeconomic impacts of allowing vs. rejecting FIP-0014.

## Executive Summary
- The current size of the network is large enough to dillute the expiring sectors in April and May.
- The network as measured in raw-bytes capacity is expected to continue growing during the V1 expiration wave.
- It remains to the community to decide about the fairness and incentivization aspects of [FIP-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md).

The code and the visualizations for this writing can be seen on the following link: https://blockscience.github.io/filecoin-metrics/notebooks/fip_0014.html

## The first wave of expiring sectors

Right now, Filecoin has about **92.3M active sectors, on which 26.2M (28% of the total) uses the V1 proof.**

An immediate concern about them is about the sectors with 6 months lifetimes, as they're starting to expire on March 26, 2021, although the **majority is going to expire between 22 April, 2021 and 28 May, 2021, peaking on 10 May, 2021**.

**That first wave makes up 6.3% of all Filecoin active sectors**, or 22.3% of all V1 sectors. In absolute terms, they're 5.8M sectors, or about 177PiB over three months.

The big picture is contained in the following chart, where waves related to the 6 months, 12 months and 18 months sectors for both V1 and V2+ sectors are identified:

![Expiring sector count, monthly](https://hackmd.io/_uploads/SyGyv8U4_.png)

A more granular view is obtained by getting the count on a daily window before 15 June. Note that the vertical axis is on logarithm scale.

![Expiring sector count, daily, before 15 june](https://hackmd.io/_uploads/SkUQD88Ed.png)

Through the above figures, we can define key dates in regards to daily sector expiration rate:

- 26 Mar, 2021: First sectors are expired
- 14 Apr, 2021: Daily sector expiration rate is above 10k per day, or 312TiB per day.
- 22 Apr, 2021: Daily sector expiration rate is above 100k per day, or 3.05PiB per day.
- 10 May, 2021: Peak of the sector expiration rate, at about 201k per day, or 6.13PiB per day.
- 28 May, 2021: Daily sector expiration rate gets below 10k per day, or 312TiB per day.


## Impact on Growth trends & Storage Power

The **current forecast points towards having 3.8 EiB of raw-byte storage power by the end of May**. This is fuelled by the continued sealing of new sectors.

![Forecasted Raw Bytes Storage Power](https://hackmd.io/_uploads/B10j88vNd.png)


---

We project that **the daily new sectors growth will be between 450k per day and 900k per day**, generating a **daily SP growth between 13.7 PiB per day to 27.5 PiB per day**.

![Forecasted Daily Sector growth](https://hackmd.io/_uploads/SypowvINO.png)

![](https://hackmd.io/_uploads/B1tw5vLNu.png)

---

The expiration of approximately 5.8M sectors between 22 April and 28 May will subtract **180k per day** from the above numbers, which is equivalent to a reduction of **40%  on the pessimistic side and 20% on the optimistic side.** Note that with more 64GiB sectors being added to the network, the actual impact tends towards the more optimistic case.


## Impact on Collateral

Right now, **Filecoin has 27.8 Million FIL locked as sector collateral, 5.8M (21%) of which are on the V1 sectors**. Notice this is relatively lower than the sector share, as the collateral for each new sector tends to increase with time.

**The 6 months V1 sectors have 1.2M FIL locked** with them (4.3% of the network total), and the event of their droppage should not be an issue for network security.

## Conclusions

From a Cryptoeconomics point of view, the network will continue to be safe and healthy on any decision regarding allowing all V1 sectors to be extended to a maxium 540 days in epoch lifetime from their activation epoch.


The decision of letting the V1 sectors expiring or not is to be put before the community, as there are multiple angles to FIP-0014 approval, which include considerations regarding fairness and behaviour incentivation, as well as other ones like environmental and waste minimization.

**Comment by jennijuju** [comment]
> # The Impact of V1 Sector Expirations on Filecoin Storage and Cryptoeconomics
> ## Background context
> Shortly after Filecoin liftoff, a security issue was reported with the v1 proofs. The issue was fixed in v1.1 proofs, which were introduced in the Filecoin network version 7 upgrade, on November 25th, 2020. As a result of this upgrade:
> 
> * All new sectors had to use v1.1 proofs
> * v1 sectors were allowed to remain on the network, **but were NOT allowed to be extended**
> 
> Since the security of these sectors is not critically compromised, we can consider allowing their extension, which was proposed in [FIP-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md). This report details the storage and cryptoeconomic impacts of allowing vs. rejecting FIP-0014.
> 
> ## Executive Summary
> * The current size of the network is large enough to dillute the expiring sectors in April and May.
> * The network as measured in raw-bytes capacity is expected to continue growing during the V1 expiration wave.
> * It remains to the community to decide about the fairness and incentivization aspects of [FIP-0014](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0014.md).
> 
> The code and the visualizations for this writing can be seen on the following link: https://blockscience.github.io/filecoin-metrics/notebooks/fip_0014.html
> 
> ## The first wave of expiring sectors
> Right now, Filecoin has about **92.3M active sectors, on which 26.2M (28% of the total) uses the V1 proof.**
> 
> An immediate concern about them is about the sectors with 6 months lifetimes, as they're starting to expire on March 26, 2021, although the **majority is going to expire between 22 April, 2021 and 28 May, 2021, peaking on 10 May, 2021**.
> 
> **That first wave makes up 6.3% of all Filecoin active sectors**, or 22.3% of all V1 sectors. In absolute terms, they're 5.8M sectors, or about 177PiB over three months.
> 
> The big picture is contained in the following chart, where waves related to the 6 months, 12 months and 18 months sectors for both V1 and V2+ sectors are identified:
> 
> ![Expiring sector count, monthly](https://camo.githubusercontent.com/be8c01517886af1bff27b8b582d0f94b3bfe8bb2dc5a828a86296f82104f34c2/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f53794779763855345f2e706e67)
> 
> A more granular view is obtained by getting the count on a daily window before 15 June. Note that the vertical axis is on logarithm scale.
> 
> ![Expiring sector count, daily, before 15 june](https://camo.githubusercontent.com/39e6c730e99611a2f0d28a0d4732511fc12e249b48d8c0de612ee92ed445d37b/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f536b555144383845642e706e67)
> 
> Through the above figures, we can define key dates in regards to daily sector expiration rate:
> 
> * 26 Mar, 2021: First sectors are expired
> * 14 Apr, 2021: Daily sector expiration rate is above 10k per day, or 312TiB per day.
> * 22 Apr, 2021: Daily sector expiration rate is above 100k per day, or 3.05PiB per day.
> * 10 May, 2021: Peak of the sector expiration rate, at about 201k per day, or 6.13PiB per day.
> * 28 May, 2021: Daily sector expiration rate gets below 10k per day, or 312TiB per day.
> 
> ## Impact on Growth trends & Storage Power
> The **current forecast points towards having 3.8 EiB of raw-byte storage power by the end of May**. This is fuelled by the continued sealing of new sectors.
> 
> ![Forecasted Raw Bytes Storage Power](https://camo.githubusercontent.com/0b8e735fa24d814022e635cab724570b0de522a0cfb204c293feb801589d8c1e/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f4231306a3838764e642e706e67)
> 
> We project that **the daily new sectors growth will be between 450k per day and 900k per day**, generating a **daily SP growth between 13.7 PiB per day to 27.5 PiB per day**.
> 
> ![Forecasted Daily Sector growth](https://camo.githubusercontent.com/e2cf95c8759e9c2186dda2d7da4a4eb5e0263b989bff6c8b16b83c842b23e11a/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f5379706f7776494e4f2e706e67)
> 
> ![](https://camo.githubusercontent.com/43a673ed7f83b55e71e17d5b26d77242eedea998ad6e536d84d91bd90b8ff2bb/68747470733a2f2f6861636b6d642e696f2f5f75706c6f6164732f4231747735764c4e752e706e67)
> 
> The expiration of approximately 5.8M sectors between 22 April and 28 May will subtract **180k per day** (5.5 PiB per day) from the above numbers, which is equivalent to a reduction of **40% on the pessimistic side and 20% on the optimistic side.** Note that with more 64GiB sectors being added to the network, the actual impact tends towards the more optimistic case.
> 
> ## Impact on Collateral
> Right now, **Filecoin has 27.8 Million FIL locked as sector collateral, 5.8M (21%) of which are on the V1 sectors**. Notice this is relatively lower than the sector share, as the collateral for each new sector tends to increase with time.
> 
> **The 6 months V1 sectors have 1.2M FIL locked** with them (4.3% of the network total), and the event of their droppage should not be an issue for network security.
> 
> ## Conclusions
> From a Cryptoeconomics point of view, the network will continue to be safe and healthy on any decision regarding allowing all V1 sectors to be extended to a maxium 540 days in epoch lifetime from their activation epoch.
> 
> The decision of letting the V1 sectors expiring or not is to be put before the community, as there are multiple angles to FIP-0014 approval, which include considerations regarding fairness and behaviour incentivation, as well as other ones like environmental and waste minimization.

This is very informative - thank you!

**Comment by arajasek** [comment]
Storage miners can vote on whether to adopt this FIP [here](https://filpoll.io/poll/7)!

**Comment by leekueha** [comment]
Answering everything with policy, why are you going to change the policy this time?
If it was a deletion policy, it should be deleted.
So, will you increase V8 540 days later?

**Comment by jennijuju** [comment]
Core devs have reviewed the [FIP-0014 survey result](https://filecoinfoundation.medium.com/thanks-for-participating-in-fip-0014-ffd739ac38ae) and final security audit and have decided that FIP-0014 will be accepted in the network. Network upgrade epoch and implementation release timelines will be announced in the [Network Updates](https://github.com/filecoin-project/community/discussions/categories/network-and-implementations) later today.

**Comment by jennijuju** [comment]
Network upgrade timeline https://github.com/filecoin-project/community/discussions/74#discussioncomment-545945

**Comment by PHABRIC77** [comment]
@danlessa can we arrange to speak about this work please? I am trying to understand the impact on the FIL economy of a number things (duration multiple, baseline crossing, staking protocols, fil financing etc). Looking for people who are modelling the FIL economy to talk through their work etc. thanks!
