### ISSUE TITLE
Free Faults on Newly Faulted Sectors of a Missed WindowPoSt

### ISSUE THREAD

**Issue by zixuanzh** [filecoin-project/FIPs#6]
## FIP-0002 Free Faults on Newly Faulted Sectors of a Missed WindowPoSt
Read: [FIP Draft](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0002.md)

## Abstract
Given the state of the network, honest miners are sometimes disproportionately penalized for operational failures by the SectorFaultDetectionFee (SP), especially when missing a WindowPoSt. This proposal reduces fees on detected faults, without sacrificing much of the security or the incentive to provide reliable storage. 
Specifically:
1. Detected faults (missing a WindowPost deadline) on 100% healthy partitions incur no fee; 
2. In partitions where some sectors are either already faulty or have declared recovery but a WindowPoSt is missed, a SectorFaultFee (FF) is incurred on those sectors;
3. Faulty sectors detected by missing a WindowPoSt incur an FF per proving period starting on the first proving deadline after they are detected faulty. Skipped Faults thus still require an FF starting on the first proving deadline.

**Comment by steven004** [comment]
For a serious storage provider, this statement `Operational failures are common and sometimes honest miners may miss a WindowPoSt deadline for reasons beyond their control. ` is not really common. With some level of redundancy design, operational failures should only happen rarely. 

I would think we have this proposal is because the WindowedPoSt failure does not really reflect the sector faults in the current network. What we often see is the power of a whole partition is removed and the penalty of whole partition failure is conducted due to a WindowedPoSt failure while actually only one or few sectors could not be access for a miner. So, what we want to improve is not the incorrect penalty but also the power, which the FIP does not touch. 

We have a mechanism to detect faults when doing wdPoSt, however, it does not really work since each sectors' nodes challenged dynamically change when there is a fault happened and the corresponding sector is removed from the proving list. The miner need to redo everything when a failure is detected, which is very hard in the limited period of a deadline. 

The power removing not fixed, and service-degraded penalty exemption makes this as a temporary workaround, instead of a long-term solution.  

Should we consider some solutions to make skipset really work? e.g. fix the challenges for each sector while keep the randomness for security?

**Comment by anorth** [comment]
This is indeed not the long term nor comprehensive solution. This is what we could achieve without introducing changes to the miner state, which we wish to avoid this close to mainnet. There are more and better ideas in earlier stages, coming to FIPs soon.

I wish I could point to a good venue for early discussion of them, but I don't think we've identified one. Let's try the #fil-specs channel in Slack.

**Comment by nicola** [comment]
This was accepted, implemented and merged. Conversations can continue, but closing the issue for tracking purposes.
