### ISSUE TITLE
Idea: extend Filecoin Plus/Verified clients to storage providers...

### ISSUE THREAD

**Issue by miyazono** [filecoin-project/FIPs#68]
This is a very long-term idea, and shouldn't be considered until after FIL+ (formerly verified clients) is deployed and working smoothly (see [FIP-3](filecoin-project/FIPS/fip-0003.md) for more on that).  Also, if this has been proposed elsewhere, just close the issue; I just figured I'd jot down the idea quickly.

Anyway, here's the thought:
It could be interesting to (one day) extend the Filecoin Plus program to also include verification of miners, instead of just clients (basically, enable the protocol to incorporate and compute on just a little bit of trust on the other side of the storage market as well).  In this model, a verified miner would be audited occasionally (e.g. to show that they have some sort of accountable legal entity, have the right kinds of redundancies & data loss prevention).  The incentive to do this would be that they don’t have to submit proofs (allowing them to save energy and decrease their operating costs).  As I see it, one big reason for PoSts is that the network is permissionless - so all accountability has to be derisked with collateral and computability.

It's a nontrivial growth in the scope for the project, but it seems like a possible way to increase scalability, as there'd be less data in the chain if there are fewer proofs.

**Comment by kaitlin-beegle** [comment]
Just reached out to the FileconPlus governance team on this one- this may actually be a programmatic change within the scope of FilecoinPlus' governance authority, which does not require a FIP.

**Comment by kaitlin-beegle** [comment]
Hey @miyazono! I think this is a great idea....old FIP item, but still relevant :) 

However, FIP0003 outlines the FilecoinPlus governance process, which allows most programmatic changes to originate, reach consensus, and be implemented solely within the FilecoinPlus ecosystem.  Though there are certain ways in which this proposal could require a FIP (for example, if there was some fee or incentive change for verified storage providers), I think this idea is best maintained within the FilecoinPlus governance repo. 

Would you mind migrating it [over there](https://github.com/filecoin-project/notary-governance/discussions)? Only flagging now because 1) opening that issue in the fil+ repo will help generate more targeted community feedback on the proposal, and 2) we're updating our FIP workflow and migrating all wish-list items out of the Issues log. 

Thank you!! If you have any questions, feel free to let me know.

**Comment by kaitlin-beegle** [comment]
Migrating for @miyazono!
