### ISSUE TITLE
Support account termination method for non-singleton actors

### ISSUE THREAD

**Issue by steven004** [filecoin-project/FIPs#78]
# Problem
Currently Filecoin does not support a full life cycle of an account from creating to termination, i.e. once an account is created, it will be always living in the network with a state, no matter it is obsoleted  by the creator or not. This leads to two issues: 

1. All obsoleted accounts, including signable ones or miners, still occupy network resources, which leads cost unnecesserily higher
2. When a user changes her account, there is always some FIL can not be transferred, which can not be ignored especially when gas base fee is pretty high. This also makes it very hard for people to use HD-wallet frequently changing addresses from privacy perspective.
3. Heavy actors (e.g. miners) can be created for almost free. They can be easily and cheaply spammed, taking a lot of network resource, and resulting in security concerns. 

# Proposed Solution
Add a termination method for non-singleton actors for vailable balance transferring and account termination. 
The termination method has one parameter as beneficiary to get all available balance 

Introduce collateral for heavy actors, e.g. miners, and the collateral will be return when it is terminated, to provide higher security guard. 

 ### Outline
This can be done step by step. For example:

1. Only support signable accounts
2. Support miner creation collateral and miner termination (only by owner under a certain condition)
3. Support paych if needed

# Discussion
This issue is intended for discussion. 

### Survey before the submission:
This proposal is first published in a WeChat article and have done a survey, got the following vote data: 
https://mp.weixin.qq.com/s/9GSvuuPb73TVIoA_foXlTQ

Do you support adding account termination method in Filecoin: 

1. **Yes**, I support it mainly because I will not lose money when I drop an address  - _47% (22/46)_
2. **Yes**, I support it mainly because it will save the network resource .  - _34% (16/46)_
3. **No**, it does not make much sense - _17% (8/46)_

**Overall, there are 81% voter support this proposal.** 

# Risks

- An account might be terminated by accident. This does not really matter, the address state can be re-created, just as a new address though we remove the state of the particular address
- An account might be associated with another one, e.g. a Miner's owner or worker. This may lead to 2 consequences if an owner or worker is terminated
> 1) One can not withdraw, or a miner can not mine; For this, we may consider the account user should take the full responsibility to check before termination
> 2) The program might panic due to the corresponding state does not exist any more, this should be carefully taken care of
> Or, we may not allow an account to be terminated when it is associated to another one, e.g. Owner, miner, controller, multisig signer, etc. 

# Other Solutions 
We may do Bitcoin like transferring, that is, 3 addresses are included is in a send message, From, To, Change addresses. But this makes send message heavier, and in most cases, the change address will be set to as From address. At the same time, it does not solve the the issue that obsoleted address still ocuppy network resource.

**Comment by kaitlin-beegle** [comment]
Hi @steven004! I am auditing all open discussion issues and noticed that there hasn't been any movement on this topic since your initial post. 

Can you provide an update? Specifically, was this issue addressed elsewhere (e.g., another repo or forum) or was offline feedback given? If not, we should reintroduce this topic to the community for consideration. 

Thanks!

**Comment by steven004** [comment]
No, this is not addressed anywhere else. This might not be on high
priority, but it should be fine to have a discussion.

**Comment by kaitlin-beegle** [comment]
Hey @steven004! In accordance with our updated workflow for FIPs, this item ought to be moved to the [FIPs Discussion Repo](https://github.com/filecoin-project/FIPs/discussions).  **Would you mind opening up a new item over there?** If you'd like, I'd also be happy to do so for you. 

Additionally, this is an enhancement that (at first appearance) would be rather technically simple to implement.  If you'd be interested in revisiting this item and potentially pursuing this as a FIP for the upcoming network upgrade, please let me know! 

Otherwise, if you're more focused on updating the Venus network for Snap Deals and working on storage provider pools, we can maintain this as a wish-list item for the future.

**Comment by steven004** [comment]
Hey Kaitlin,

Please help to move it to the FIPs Discussion Repo. Thanks.

And, I would think this is not a high priority. It should be quite fine to
maintain it as a wish-list item.

Best,
Steven
