### ISSUE TITLE
FIP Proposal: Ability to extend life of a sector with deals from lotus client

### ISSUE THREAD

**Issue by Angelo-gh3990** [filecoin-project/FIPs#95]
Is your feature request related to a problem? Please describe.
Unable to extend the life of a sector that has deals in it from a client side.

Describe the solution you'd like
Extending a sector with deals expiration time with the amount of weeks needed.
On the client side it would be great to be able to specify it's an active deal and request a reseal with a new expiration date.
Resealing it as a new sector at the same miner would be fine, the data gets copied in a new sector and sealed again with new collateral and the rest of the process. Probably the easiest way to do it, as everything is available at the miner.

Describe alternatives you've considered
I considered copying the data from the old sector back to my client, and requesting a new deal..

Additional context

**Comment by jennijuju** [comment]
To be clear, the thing you want to discuss is how a client can initiate a deal extention?

**Comment by gh3990** [comment]
You are right, but image I'm a client and I have a deal running with a certain miner that's about to expire. It would be great to be able to extend that specific deal from a client side based on the new current pricing a miner would ask for it. The reason is because I have customers right now asking to make a deal for 4 years, but there is no support for that right now. But I do need to store the data that long on the network. That's why a deal extension client command would make sense in my opinion. The other option, which is the case right now is to send the data again and get it sealed again. Seems a bit like extra work for a storage contract for 4 years or longer. I will have to make that same deal and transfer the data 3 times or more during the life time of the storage contract I made with a customer.

**Comment by kaitlin-beegle** [comment]
Hi @gh3990! I'm auditing open discussion issues and noticed that this topic was still outstanding.  I'd like to help move this forward, but want to first make sure I understand the proposal correctly.  

It seems to me that there are two distinct requests here: 
1) Create a command-line instruction so clients can request deal extensions for a specified amount of time, and;
2) An extension to the maximum lifetime of a sector, from 18 months to 4+ years

Is this interpretation correct?  If so, and you still believe this is a topic that ought to be pursued, I would be happy to circulate the discussion post and solicit additional feedback from the Filecoin community. 

If input is constructive and generally supportive, would you be able/interested in writing the FIP draft? See: 'What belongs in a successful FIP' in [FIP0001](https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0001.md)

**Comment by gh3990** [comment]
@kaitlin-beegle that would be great if it could get some more attention.
And yes request 1 definitely, request 2 isn't necessary because if request 1 would be available the second request wouldn't be necessary.

I will plan some time to write up a FIP. Can you send that link to the FIP draft again, it doesn't seem to work.

Thank you

**Comment by AthenaPoolOfficial** [comment]
We agree with the idea of‘extend sector's life with deals from lotus client ’instead of  sealing sectors again. 
And only after paying off the sum payable of storage can SP extend the sector's life successfully.

In addition,some questions need us to discuss:
1.Does the storage unit-price support the change during the extension?  If SP can change the price, we also need to look out for the locked amount that have been calculated by the unit-price。
2.If it is more reasonable for clients to choose whether to extend automatically or not when they submit PublishStorageDeals? My rough idea is that the clientscan set a expectation price,and the clients won't extend by default when the expectation price lower than the unit-price.At the same time,the clients also can choose their expectation price and whether to extend manually or automatically.
3.Because the sector has a maximum lifetime limitation of 5 years now. Is it allowed to extend sector's life without any deadline?

**Comment by kaitlin-beegle** [comment]
Hi there @Angelo-gh3990! 

It looks like this idea is still outstanding! However, we have a new FIPs workflow in place, and need to migrate all outstanding items from the Issues log to the FIPs Discussion Forum.  **If you are still interested in pursuing this issue, could you please migrate this ASAP?** All you have to do is go to the [Discussion Forum](https://github.com/filecoin-project/FIPs/discussions), create a new discussion, and link to this post. 

Let me know if you have any questions!

**Comment by jennijuju** [comment]
@Angelo-gh3990 

>Extending a sector with deals expiration time with the amount of weeks needed.
On the client side it would be great to be able to specify it's an active deal and request a reseal with a new expiration date.

Could you please confirm whether you are looking for client to initiate a new deal with the SP they know already have the data, and then the SP can seal the deal into a sector using the local data (without going through the data transfer from the client again?)

or

you want to discuss the option to be able to extend the existing deal expiration on chain?

**Comment by Angelo-gh3990** [comment]
@jennijuju , it's the later ... If the deal is extended on chain I assume the SP will be paid to keep serving the deal content. That would be the best situation and the most easy way on the client side. Thanks

@kaitlin-beegle ok, got it. I'll do that in the next couple of days. Thanks
